name: coderefinery
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>3.9
  - click=8.0.4
  - ipywidgets=7.6.5
  - jupyterlab=3.3.0
  - jupyterlab-git=0.34.2
  - matplotlib=3.5.1
  - numpy=1.22.3
  - nbdime=3.1.1
  - pandas=1.4.1
  - pytest=7.0.1
  - seaborn=0.11.2
  - snakemake-minimal=7.1.1
  - sphinx=4.4.0
  - sphinx_rtd_theme=1.0.0
  - myst-parser=0.17.0
  - sphinx-autobuild
